version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - RUN_MIGRATIONS_AND_SEEDS=${RUN_MIGRATIONS_AND_SEEDS}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
      - APP_URL=${APP_URL}
    depends_on:
      - db

  db:
    image: postgres:12-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
