name: Deploy to Server
on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /usr/share/nginx/${{ secrets.REPO_NAME }}/
          git checkout ${{ secrets.MAIN_BRANCH }}
          git pull origin ${{ secrets.MAIN_BRANCH }}
          docker-compose down
          docker-compose up --build
